# Generated by Django 4.0.5 on 2022-07-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_delete_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
