# Generated by Django 4.0.5 on 2022-07-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Trip',
        ),
    ]
