# Generated by Django 4.0.5 on 2022-07-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_rename_movie_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='title',
            new_name='product_name',
        ),
    ]
