# Generated by Django 4.0.5 on 2022-08-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='stock',
        ),
    ]
