# Generated by Django 4.0.5 on 2022-08-05 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_trip_description_remove_trip_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='occupant_first_name',
            new_name='occupant_username',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='occupant_last_name',
        ),
    ]
